# Sets up R environment with package caching, TinyTeX, and libcurl.
#
# Author: John Grimes

name: Setup R
description: Sets up R with package caching, TinyTeX, libcurl, and optionally Pandoc.

inputs:
  r-version:
    description: R version to install.
    required: false
    default: "4.1.3"
  install-pandoc:
    description: Install Pandoc for documentation generation.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version }}
        use-public-rspm: true

    - name: Set up Pandoc
      if: inputs.install-pandoc == 'true'
      uses: r-lib/actions/setup-pandoc@v2

    - name: Cache R packages
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/Library
        key: r-packages-${{ runner.os }}-${{ hashFiles('lib/R/DESCRIPTION.src') }}
        restore-keys: r-packages-${{ runner.os }}-

    # TinyTeX and libcurl are required for building the R package documentation.
    - name: Install TinyTeX and libcurl
      shell: bash
      run: |
        wget --max-redirect=0 -qO- "https://tinytex.yihui.org/install-bin-unix.sh" | sh
        echo "$HOME/bin" >> $GITHUB_PATH
        sudo apt-get install -y libcurl4-openssl-dev
