kind: Deployment
apiVersion: apps/v1
metadata:
  name: pathling-deployment
spec:
  selector:
    matchLabels:
      app: pathling-server
  template:
    metadata:
      labels:
        app: pathling-server
    spec:
      containers:
        - name: pathling-server
          image: {{ .Values.pathling.image | quote }}
          imagePullPolicy: {{ .Values.pathling.deployment.imagePullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 4040
            - containerPort: 7077
            - containerPort: 7078
          resources:
            requests: {{ toJson .Values.pathling.resources.requests }}
            limits: {{ toJson .Values.pathling.resources.limits }}
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 5
            failureThreshold: 36
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts: {{ toJson .Values.pathling.volumeMounts }}
          {{- if gt (add (len .Values.pathling.config) (len .Values.pathling.secretConfig)) 0 }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: {{ printf "-Xmx%s  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED %s" .Values.pathling.resources.maxHeapSize .Values.pathling.additionalJavaOptions }}
            - name: spark.driver.host
              value: pathling-driver
            - name: spark.driver.port
              value: "7077"
            - name: spark.blockManager.port
              value: "7078"
            - name: spark.driver.bindAddress
              value: 0.0.0.0
            {{- range $configKey, $configValue := .Values.pathling.config }}
            - name: {{ $configKey }}
              value: {{ $configValue | quote }}
            {{- end }}
            {{- range $configKey, $configValue := .Values.pathling.secretConfig }}
            - name: {{ $configKey }}
              valueFrom:
                secretKeyRef:
                  name: pathling-secrets
                  key: {{ $configKey }}
            {{- end }}
          {{- end }}
      volumes: {{ toJson .Values.pathling.volumes }}
      serviceAccountName: {{ .Values.pathling.serviceAccount }}
      imagePullSecrets: {{ toJson .Values.pathling.imagePullSecrets }}
      tolerations: {{ toJson .Values.pathling.tolerations }}
      affinity: {{ toJson .Values.pathling.affinity }}
  strategy:
    type: {{ .Values.pathling.deployment.strategy }}
{{- if gt (len .Values.pathling.secretConfig) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pathling-secrets
data:
  {{- range $configKey, $configValue := .Values.pathling.secretConfig }}
  {{ $configKey }}: {{ $configValue | b64enc }}
  {{- end }}
{{- end }}
