kind: Deployment
apiVersion: apps/v1
metadata:
  name: pathling-jupyter-deployment
spec:
  selector:
    matchLabels:
      app: pathling-jupyter
  template:
    metadata:
      labels:
        app: pathling-jupyter
    spec:
      containers:
        - name: pathling-jupyter
          image: {{ .Values.pathlingJupyter.image | quote }}
          imagePullPolicy: {{ .Values.pathlingJupyter.deployment.imagePullPolicy }}
          ports:
            - name: jupyter
              containerPort: 8888
            - name: spark-ui
              containerPort: 4040
          resources:
            requests: {{ toJson .Values.pathlingJupyter.resources.requests }}
            limits: {{ toJson .Values.pathlingJupyter.resources.limits }}
          {{- if .Values.pathlingJupyter.persistence.enabled }}
          volumeMounts:
            - name: notebooks
              mountPath: /home/jovyan
          {{- else }}
          volumeMounts: {{ toJson .Values.pathlingJupyter.volumeMounts }}
          {{- end }}
          {{- if gt (add (add (len .Values.pathlingJupyter.config) (len .Values.pathlingJupyter.secretConfig)) (len .Values.pathlingJupyter.spark)) 0 }}
          env:
            {{- range $configKey, $configValue := .Values.pathlingJupyter.config }}
            - name: {{ $configKey }}
              value: {{ $configValue | quote }}
            {{- end }}
            {{- range $configKey, $configValue := .Values.pathlingJupyter.secretConfig }}
            - name: {{ $configKey }}
              valueFrom:
                secretKeyRef:
                  name: pathling-jupyter-secrets
                  key: {{ $configKey }}
            {{- end }}
            {{- range $sparkKey, $sparkValue := .Values.pathlingJupyter.spark }}
            - name: {{ $sparkKey | replace "." "_" | upper }}
              value: {{ $sparkValue | quote }}
            {{- end }}
          {{- end }}
      {{- if .Values.pathlingJupyter.persistence.enabled }}
      volumes:
        - name: notebooks
          persistentVolumeClaim:
            claimName: pathling-jupyter-pvc
      {{- else }}
      volumes: {{ toJson .Values.pathlingJupyter.volumes }}
      {{- end }}
      tolerations: {{ toJson .Values.pathlingJupyter.tolerations }}
      affinity: {{ toJson .Values.pathlingJupyter.affinity }}
      securityContext: {{ toJson .Values.pathlingJupyter.securityContext }}
  strategy:
    type: {{ .Values.pathlingJupyter.deployment.strategy }}
{{- if gt (len .Values.pathlingJupyter.secretConfig) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pathling-jupyter-secrets
data:
  {{- range $configKey, $configValue := .Values.pathlingJupyter.secretConfig }}
  {{ $configKey }}: {{ $configValue | b64enc }}
  {{- end }}
{{- end }}
